### ISSUE TITLE
Can't replace a tag without a patch version

### ISSUE THREAD

**Issue by y-yagi** [suzuki-shunsuke/pinact#817]
## pinact version

Please use the latest version.

```console
$ pinact -v
pinact version  ()
```

Note: I installed `pinact` by `go install`(`go install github.com/suzuki-shunsuke/pinact/cmd/pinact@latest`). 

## Environment

* OS (Windows, Linux, macOS, etc): Linux(Ubuntu)
* CPU Architecture (amd64, arm64, etc): x86_64

## Overview

Can't replace a tag without a patch version(e.g. `v1.6`).

## How to reproduce

* workflow file
* executed command and output

[Write good `How to reproduce`](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce)

workflow file

```yaml
name: Turbo

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.6
```

```console
$ pinact run .github/workflows/turbo.yml 
```

## Expected Behaviour

The tag(`@v1.6`) is changed to a commit hash.

## Actual Behaviour

The tag isn't changed to a commit hash.

## Important Factoids

It seems that this type of tag isn't considered.
https://github.com/suzuki-shunsuke/pinact/blob/e926c8bc580049a1fad23bb19d2030aa11c181e0/pkg/controller/run/parse_line.go#L16-L19

But, there is an action that uses this kind of tag.
https://github.com/rharkor/caching-for-turbo/tags

## References

*
