### ISSUE TITLE
Introduce a syntax to distinguish fixed strings and regular expressions

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/pinact#846]
## Feature Overview

Introduce a syntax to distinguish fixed strings and regular expressions.

## Why is the feature needed?

> Please explain the problem you want to solve.

## Example Code

```yaml
files:
  - pattern: action.yaml
    pattern_type: glob # regexp, fixed_string

ignore_actions:
  - name: ^suzuki-shunsuke/
    name_type: regexp # fixed_string, Current: regexp, v3: fixed_string
    ref: ^main$
    ref_type: regexp # fixed_string, Current: regexp, v3: fixed_string
```

Add

- `files[].pattern_format`
- `ignore_actions[].name_format`
- `ignore_actions[].ref_format`

Available values: `fixed_string`, `glob`, `regexp`

## ⚠ Breaking Changes

Default value of `*_format` is changed.

`regexp` (v2) => `fixed_string` (v3)

## Note

- https://github.com/suzuki-shunsuke/pinact/pull/845#issuecomment-2749902716
