### ISSUE TITLE
Add Docker Action Support for Digest Pinning

### ISSUE THREAD

**Issue by mkusaka** [suzuki-shunsuke/pinact#847]
## Feature Request

First, I'd like to express my sincere gratitude for creating and maintaining pinact. It has been an incredibly useful tool for securing our GitHub Actions workflows! 🙏

### Feature Overview

Add support for pinning Docker container actions to their SHA256 digests in GitHub Workflow files, similar to how pinact handles standard GitHub Actions.

This would enable:Automatic conversion of `docker://{image}:{tag}` to `docker://{image}:{tag}@{sha}` format

### Why is the feature needed?

Docker-based actions are widely used but currently create security gaps in pinact's protection:
1. **Security Risk**: Container tags are mutable like GitHub Action tags
2. **Inconsistency**: Only "uses:" actions get pinned while Docker actions remain vulnerable
3. **Manual Error Prone**: Current workaround of manual digest insertion causes pinact errors and requires registry lookups

### Example Code

**Current Workflow (Unpinned Docker Action)**:

```
name: zizmor-security-check
on:
  push:
    paths:
      - ".github/workflows/**"

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Zizmor security check
        uses: docker://ghcr.io/woodruffw/zizmor:latest
        with:
          args: --format plain .github/workflows/
```

**Desired Workflow (Pinned Docker Action)**:

```
name: zizmor-security-check
on:
  push:
    paths:
      - ".github/workflows/**"

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run Zizmor security check
        uses: docker://ghcr.io/woodruffw/zizmor:1.5.2@sha256:f0bbe68825022e3336389e754d4c8a28928246275e9c549251997f25318896f1
        with:
          args: --format plain .github/workflows/
```

**Current Error When Manually Pinned**:

```
$ pinact run
ERRO[0000] parse a line                                  action="docker://ghcr.io/woodruffw/zizmor:1.5.2@sha256:f0bbe68825022e3336389e754d4c8a28928246275e9c549251997f25318896f1" error="action can't be pinned" pinact_version=2.1.0 program=pinact workflow_file=.github/workflows/zizmor-security-check.yml
```

**Desired Behavior**:

```
$ pinact run
# Should recognize and validate existing digests instead of throwing an error
```

This feature would make pinact a complete security solution for all action types in GitHub Workflows, including Docker-based actions. 🛡️
