### ISSUE TITLE
Unexpected downgrading is occurred.

### ISSUE THREAD

**Issue by mythrnr** [suzuki-shunsuke/pinact#910]
## pinact version

```console
$ pinact -v
pinact version 3.0.3 (307194e27c916f53c084bbc1fb560a1452fb2dea)
```

## Environment

* OS (Windows, Linux, macOS, etc): `macOS`
* CPU Architecture (amd64, arm64, etc): `arm64`

## Overview

When a new release is created within the previous major version, it is treated as the latest.
So, unexpected downgrading is occurred.  
I found this issue by [actions/setup-go](https://github.com/actions/setup-go/releases).

## How to reproduce

workflow file ( using `v5.4.0` )

```yaml
jobs:
  job:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b" # v5.4.0
        with:
          go-version: "1.24"
```

```console
$ pinact run -u
```

## Expected Behaviour

The workflow file is not changed.

## Actual Behaviour

The workflow file is changed to `v4.2.1`

```yaml
jobs:
  job:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639" # v4.2.1
        with:
          go-version: "1.24"
```

## References

- [actions/setup-go](https://github.com/actions/setup-go/releases)
