### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by 5ouma** [suzuki-shunsuke/pinact#930]
Since `name` and `description` need to be added to the config file in this repository, please let me know.
Please see the actual config example from [actionlint one](https://github.com/rhysd/actionlint/blob/main/.pre-commit-hooks.yaml).

**Comment by Zegnat** [comment]
A variation on what xenophonf posted above.

I did not want to ensure that the right version of pinact was locally installed everywhere, so this wrapper can make sure that prek (a pre-commit runner) handles the version for me:

```toml
[[repos]]
repo = "https://github.com/ref-app/prek-pinact"
rev = "8e837677fdfcf9bc7a88f7adae3f5cd798445018" # frozen: v4.1.0
hooks = [{ id = "pinact" }]
```

Note: the `rev` is a result of [`prek auto-update`](https://prek.j178.dev/reference/cli/#prek-auto-update). This is a hash from the prek-pinact repo, and does not strictly refer to a version of pinact.
