### ISSUE TITLE
Getting a long tag warning when the sha _does_ match the comment

### ISSUE THREAD

**Issue by sudoforge** [suzuki-shunsuke/pinact#939]
## pinact version

Please use the latest version.

```console
$ pinact -v
3.0.5
```

## Environment

* OS: Linux
* CPU Architecture: amd64

## How to reproduce

**workflow file**

```
name: example

on:
  workflow_call:

jobs:
  example:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v17

      - run: echo "done"

```

**pinact command and output**

```
➜ pinact run --verify                                   
WARN[0000] a long tag whose SHA is same as SHA of the version annotation isn't found  action=DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 pinact_version=3.0.5 program=pinact version_an
notation=v17 workflow_file=.github/workflows/build-and-test.yml
```

## Expected Behaviour

This is a pinact-generated commit hash from the original reference `DeterminateSystems/nix-installer-action@v17`. Given that it is a valid commit hash, and the comment matches a ref (tag) that has that commit hash, I expect no warning.

**Verification that GitHub's API has this commit hash associated with the tag**

```
➜ gh api /repos/DeterminateSystems/nix-installer-action/tags --jq '.[] | select(.name=="v17") | .commit.sha'
21a544727d0c62386e78b4befe52d19ad12692e3
```

## Actual Behaviour

I get a warning.
