### ISSUE TITLE
Get a GitHub Access Token from 1password

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/pinact#951]
## Feature Overview

Get a GitHub Access Token from 1password.

## Why is the feature needed?

> Please explain the problem you want to solve.

To manage GitHub Access Token securely.
Exposing a GitHub Access token to environment variables aren't secure as any process can read it.

## Example Code

```sh
export AQUA_ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN=xxx
```

## Note

- https://github.com/1Password/onepassword-sdk-go
- https://github.com/aquaproj/aqua/issues/3068

**Comment by philpennock** [comment]
Another approach to consider: give `pinact.yaml` a directive `ghtoken.command`.

Then someone who uses 1Password might use:

```yaml
ghtoken:
  command:
    - op
    - ready
    - "--"
    - op://VaultName/ItemName/github-token
```

Someone else, using BitWarden, might use:

```yaml
ghtoken:
  command:
    - bw
    - get
    - password
    - github-token
```

### Pros

1. The `pinact` binary does not need to grow bigger with dependencies for various blessed SDKs
2. People can use whatever password manager they like
3. You don't need to force a naming convention on the vault or item

### Cons

1. The user will need to manage having a valid token, or prompting to authenticate, in their command invocation
