### ISSUE TITLE
`x.y` tags throw warnings

### ISSUE THREAD

**Issue by p-linnane** [suzuki-shunsuke/pinact#979]
## pinact version

pinact version 3.1.1

## Environment

* OS (Windows, Linux, macOS, etc): macOS
* CPU Architecture (amd64, arm64, etc): arm64

## How to reproduce

**workflow file**

```yaml
name: DCO Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: tisonkun/actions-dco@f1024cd563550b5632e754df11b7d30b73be54a5 # v1.1
```

```console
$ ╰─ pinact run
WARN[0002] a long tag whose SHA is same as SHA of the version annotation isn't found  action=tisonkun/actions-dco@f1024cd563550b5632e754df11b7d30b73be54a5 pinact_version=3.1.1 program=pinact version_annotation=v1.1 workflow_file=.github/workflows/dco_check.yaml
```

## Expected Behaviour

I expected pinact to exit silently

## Actual Behaviour

Warning as seen above

## Important Factoids

It seems like the issue has to do with the full tag being v1.1 rather than v1.1.0
